"""add active column

Revision ID: 2a8164d12562
Revises: 10bb88fcd8db
Create Date: 2025-06-24 23:01:59.066252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8164d12562'
down_revision: Union[str, None] = '10bb88fcd8db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('resources', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'active')
    # ### end Alembic commands ###
