"""UUIDs migration

Revision ID: 3c83d29b2ce3
Revises: d19fd41c16c9
Create Date: 2025-05-19 17:14:41.331704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c83d29b2ce3'
down_revision: Union[str, None] = 'd19fd41c16c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('external_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_chat_sessions_external_id'), 'chat_sessions', ['external_id'], unique=True)
    op.create_foreign_key(None, 'resource_chunks', 'resources', ['resource_id'], ['id'])
    op.add_column('users', sa.Column('external_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_column('users', 'external_id')
    op.drop_constraint(None, 'resource_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_external_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'external_id')
    # ### end Alembic commands ###
