"""Add role column in user

Revision ID: 62ac06a805df
Revises: 66c4f8443877
Create Date: 2025-06-17 10:26:57.257891

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62ac06a805df"
down_revision: Union[str, None] = "6bf231d10e35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role_enum = sa.Enum("admin", "user", name="userrole")


def upgrade() -> None:
    """Upgrade schema."""
    user_role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column("users", sa.Column("role", user_role_enum, nullable=True))

    op.execute("UPDATE users SET role = 'user'")

    op.alter_column("users", "role", existing_type=user_role_enum, nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
