"""Add role column in user

Revision ID: 62ac06a805df
Revises: 66c4f8443877
Create Date: 2025-06-17 10:26:57.257891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ac06a805df'
down_revision: Union[str, None] = '66c4f8443877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=True))
    op.execute("UPDATE users SET role = 'user'")
    op.alter_column('users', 'role', existing_type=sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
