"""add chat session name

Revision ID: 6bf231d10e35
Revises:
Create Date: 2025-06-03 15:46:48.367261

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6bf231d10e35"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "chat_messages",
        "chat_sessions",
        ["chat_session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("chat_sessions", sa.Column("session_name", sa.Text(), nullable=True))
    op.create_foreign_key(None, "resources", "users", ["updated_by_id"], ["id"])
    op.create_foreign_key(None, "resources", "users", ["created_by_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "resources", type_="foreignkey")
    op.drop_constraint(None, "resources", type_="foreignkey")
    op.drop_column("chat_sessions", "session_name")
    op.drop_constraint(None, "chat_messages", type_="foreignkey")
    # ### end Alembic commands ###
