"""resource fields  migration

Revision ID: d19fd41c16c9
Revises: c9b3e4a0842c
Create Date: 2025-05-15 17:09:42.755095

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d19fd41c16c9"
down_revision: Union[str, None] = "c9b3e4a0842c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sources", sa.Column("created_by_id", sa.Integer(), nullable=True))
    op.add_column("sources", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.execute("UPDATE sources SET created_by_id = 1")
    op.execute("UPDATE sources SET created_at = NOW()")
    op.alter_column("sources", "created_by_id", nullable=False)
    op.alter_column("sources", "created_at", nullable=False)
    op.add_column("sources", sa.Column("updated_by_id", sa.Integer(), nullable=True))
    op.add_column("sources", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.create_foreign_key(None, "sources", "users", ["created_by_id"], ["id"])
    op.create_foreign_key(None, "sources", "users", ["updated_by_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sources", type_="foreignkey")
    op.drop_constraint(None, "sources", type_="foreignkey")
    op.drop_column("sources", "updated_at")
    op.drop_column("sources", "updated_by_id")
    op.drop_column("sources", "created_at")
    op.drop_column("sources", "created_by_id")
    # ### end Alembic commands ###
